services:
    laravel.test:
        extends:
            file: docker/docker-compose.laravel.yml
            service: laravel
        container_name: "${COMPOSE_PROJECT_NAME}-laravel.test"
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        restart: unless-stopped
        depends_on:
            mysql:
                condition: service_healthy
    queue:
        extends:
            file: docker/docker-compose.laravel.yml
            service: laravel
        container_name: "${COMPOSE_PROJECT_NAME}-queue"
        command: php artisan queue:work
        restart: unless-stopped
        depends_on:
            mysql:
                condition: service_healthy
    schedule:
        extends:
            file: docker/docker-compose.laravel.yml
            service: laravel
        container_name: "${COMPOSE_PROJECT_NAME}-schedule"
        command: php artisan schedule:work
        restart: unless-stopped
        depends_on:
            mysql:
                condition: service_healthy
    websockets:
        extends:
            file: docker/docker-compose.laravel.yml
            service: laravel
        container_name: "${COMPOSE_PROJECT_NAME}-websockets"
        ports:
            - '${REVERB_PORT:-8080}:${REVERB_PORT:-8080}'
        command: php artisan reverb:start --host=0.0.0.0 --port='${REVERB_PORT:-8080}'
    mysql:
        container_name: "${COMPOSE_PROJECT_NAME}-mysql"
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: "exit 0"
        restart: unless-stopped
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local

